<a href="https://colab.research.google.com/github/FauxGrit/Titanic-Fairness/blob/main/Fairness_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Objective: Explore Fairness in Titanic Survival Model
 **Objective**: This code provides an iniital exploration for building a model to predict Airbnb prices.  In particular we are interested in learning which features are most important.

**Assumptions**: 
1. N/A

**Open Questions**:  
1. N/A

**Reference Links**
1. N/A

### Check Python Version

In [1]:
import sys
print("Python version")
print (sys.version)
print("Version info.")
print (sys.version_info)

Python version
3.8.15 (default, Oct 12 2022, 19:14:39) 
[GCC 7.5.0]
Version info.
sys.version_info(major=3, minor=8, micro=15, releaselevel='final', serial=0)


### Importing Necessary Libraries

In [44]:
!pip install aequitas==0.42.0

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import warnings, os, xlrd, pickle
import time

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import openpyxl

from sklearn.model_selection import train_test_split
from sklearn.metrics import *
from sklearn import metrics as sklearn_metrics
from sklearn import linear_model, preprocessing
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
import statsmodels.api as sm
from sklearn.preprocessing import OneHotEncoder
from sklearn import discriminant_analysis
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
# from catboost import CatBoostClassifier

from aequitas.group import Group
from aequitas.bias import Bias
from aequitas.fairness import Fairness
import aequitas.plot as ap


# from pycaret.classification import *   ## <--- uncomment to run!!!
from geopy.distance import geodesic
from math import cos, sqrt

import seaborn as sns
from plotly.offline import init_notebook_mode, iplot
import plotly.figure_factory as ff
import cufflinks
cufflinks.go_offline()
cufflinks.set_config_file(world_readable=True, theme='pearl')
import plotly.graph_objs as go
import plotly
from plotly import tools

init_notebook_mode(connected=True)
pd.set_option('display.max_columns', 100)

# Supress warnings for cleaner presentation
# Turn off durng development!!!
%matplotlib inline
warnings.filterwarnings('ignore')

# Gather Data
Airbnb data from Kaggle https://www.kaggle.com/ivanovskia1/nyc-airbnb-rental-data-october-2017 .

**Preprocessing prior to data load:**
Significant data cleaning done using OpenRefine.


### Load Data into Notebook
* Load CSV file. It must be in same directory location as Jupyter Notebook (or add path to code).
* Print first five rows to confirm data load.
* Print shape to see how many rows and columns.

#### Merged and Cleaned Data

In [4]:
data_url = 'https://raw.githubusercontent.com/FauxGrit/Titanic-Fairness/main/train.csv'
df0 = pd.read_csv(data_url)

df0.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [5]:
# Print shape of dataframe to determine number of rows and columns
print("Cleaned Airbnb Data\nNumber of rows: ", df0.shape[0], "\nNumber of columns: ", df0.shape[1])

Cleaned Airbnb Data
Number of rows:  891 
Number of columns:  12


# Basic Data Exploration

### Numerical Data Basic Stats

#### Clean and Merged Airbnb Data

In [6]:
df0['Children'] = 0
df0.loc[df0['Age'] < 19, 'Children'] = 1

df0.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Children  
0      0         A/5 21171   7.2500   NaN        S         0  
1      0          PC 17599  71.2833   C85        C         0  
2      0  STON/O2. 3101282   7.9250   NaN        S         0  
3      0            113803  53.1000  C123        S         0  
4      0            373450   8.0500   NaN        S         0

In [8]:
# Fill NaN values
df0['Age'] = df0['Age'].fillna(df0['Age'].mean())
df0['Fare'] = df0['Fare'].fillna(df0['Fare'].mean())
df0['Embarked'] = df0['Embarked'].fillna('Empty')

df0.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  Children  
0      0         A/5 21171   7.2500   NaN        S         0  
1      0          PC 17599  71.2833   C85        C         0  
2      0  STON/O2. 3101282   7.9250   NaN        S         0  
3      0            113803  53.1000  C123        S         0  
4      0            373450   8.0500   NaN        S         0

In [9]:
df1 = pd.get_dummies(data=df0, columns=['Sex','Embarked'])
df1.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0      1      0   
2                             Heikkinen, Miss. Laina  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0      1      0   
4                           Allen, Mr. William Henry  35.0      0      0   

             Ticket     Fare Cabin  Children  Sex_female  Sex_male  \
0         A/5 21171   7.2500   NaN         0           0         1   
1          PC 17599  71.2833   C85         0           1         0   
2  STON/O2. 3101282   7.9250   NaN         0           1         0   
3            113803  53.1000  C123         0           1         0   
4            373450   8.0500   NaN         0           0         1   

   Embarked_C  Embarked_Empty  Embarked_Q  Embarked_S  
0           0               0           0           1  
1           1               0           0           0  
2           0               0           0           1  
3           0               0           0           1  
4           0               0           0           1

In [10]:
# Drop 'PassengerId','Name','Ticket','Cabin' since not useful
df1.drop(['PassengerId','Name','Ticket','Cabin', 'Sex_female'], axis=1, inplace=True)
df1.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Children  Sex_male  \
0         0       3  22.0      1      0   7.2500         0         1   
1         1       1  38.0      1      0  71.2833         0         0   
2         1       3  26.0      0      0   7.9250         0         0   
3         1       1  35.0      1      0  53.1000         0         0   
4         0       3  35.0      0      0   8.0500         0         1   

   Embarked_C  Embarked_Empty  Embarked_Q  Embarked_S  
0           0               0           0           1  
1           1               0           0           0  
2           0               0           0           1  
3           0               0           0           1  
4           0               0           0           1

In [11]:
df1.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Children',
       'Sex_male', 'Embarked_C', 'Embarked_Empty', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [12]:
df1.describe().T

count       mean        std   min      25%        50%   75%  \
Survived        891.0   0.383838   0.486592  0.00   0.0000   0.000000   1.0   
Pclass          891.0   2.308642   0.836071  1.00   2.0000   3.000000   3.0   
Age             891.0  29.699118  13.002015  0.42  22.0000  29.699118  35.0   
SibSp           891.0   0.523008   1.102743  0.00   0.0000   0.000000   1.0   
Parch           891.0   0.381594   0.806057  0.00   0.0000   0.000000   0.0   
Fare            891.0  32.204208  49.693429  0.00   7.9104  14.454200  31.0   
Children        891.0   0.156004   0.363063  0.00   0.0000   0.000000   0.0   
Sex_male        891.0   0.647587   0.477990  0.00   0.0000   1.000000   1.0   
Embarked_C      891.0   0.188552   0.391372  0.00   0.0000   0.000000   0.0   
Embarked_Empty  891.0   0.002245   0.047351  0.00   0.0000   0.000000   0.0   
Embarked_Q      891.0   0.086420   0.281141  0.00   0.0000   0.000000   0.0   
Embarked_S      891.0   0.722783   0.447876  0.00   0.0000   1.000000   1.0   

                     max  
Survived          1.0000  
Pclass            3.0000  
Age              80.0000  
SibSp             8.0000  
Parch             6.0000  
Fare            512.3292  
Children          1.0000  
Sex_male          1.0000  
Embarked_C        1.0000  
Embarked_Empty    1.0000  
Embarked_Q        1.0000  
Embarked_S        1.0000

In [13]:
#Separate Input & Response Variables
X = df1.iloc[:,df1.columns != 'Survived'].values
y = df1.iloc[:, 0].values

In [14]:
#Split into Training / Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [15]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
attributes_and_reference_groups={'Age_Level': 'Adults'}
attributes_to_audit = list(attributes_and_reference_groups.keys())

# False Positive Rate --> "It's gonna sink, but we predict you will survive"
metrics = ['fpr']

disparity_tolerance = 1.2

In [17]:
df_fair = pd.DataFrame(X_test, columns = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Children',
       'Sex_male', 'Embarked_C', 'Embarked_Empty', 'Embarked_Q', 'Embarked_S'])

df_fair['label_value'] = y_test

df_fair['Age_Level'] = 'Adults'
df_fair.loc[df_fair['Children'] > 0, 'Age_Level'] = 'Children'

# df_fair.tail(10)

# Initialize Aequitas
g = Group()
b = Bias()

#Random Forrest Classifier

In [18]:
rf = RandomForestClassifier(max_depth=3, random_state=0)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=3, random_state=0)

In [19]:
# Test Data
sklearn_metrics.confusion_matrix(y_test, rf.predict(X_test))

array([[129,  10],
       [ 29,  55]])

In [20]:
# Accuracy
rf.score(X_test, y_test)

0.8251121076233184

In [21]:
df_fair['score'] = rf.predict(X_test)

# get_crosstabs returns a dataframe of the group counts and group value bias metrics.
xtab, _ = g.get_crosstabs(df_fair, attr_cols=attributes_to_audit)
bdf = b.get_disparity_predefined_groups(xtab, original_df=df_fair, ref_groups_dict=attributes_and_reference_groups)

ap.disparity(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

get_disparity_predefined_group()


alt.LayerChart(...)

In [22]:
ap.absolute(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

alt.LayerChart(...)

#XGBoost Classifier

In [23]:
xg = xgb.XGBClassifier()
xg.fit(X_train, y_train)

XGBClassifier()

In [24]:
# Test Data
sklearn_metrics.confusion_matrix(y_test, xg.predict(X_test))

array([[127,  12],
       [ 21,  63]])

In [25]:
# Accuracy
xg.score(X_test, y_test)

0.852017937219731

In [26]:
df_fair['score'] = xg.predict(X_test)

# get_crosstabs returns a dataframe of the group counts and group value bias metrics.
xtab, _ = g.get_crosstabs(df_fair, attr_cols=attributes_to_audit)
bdf = b.get_disparity_predefined_groups(xtab, original_df=df_fair, ref_groups_dict=attributes_and_reference_groups)

ap.disparity(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

get_disparity_predefined_group()


alt.LayerChart(...)

In [27]:
ap.absolute(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

alt.LayerChart(...)

#Gradient Boosting Classifier

In [28]:
GradientBoostingClassifier
gb = GradientBoostingClassifier()
gb.fit(X_train, y_train)

GradientBoostingClassifier()

In [29]:
# Test Data
sklearn_metrics.confusion_matrix(y_test, gb.predict(X_test))

array([[127,  12],
       [ 23,  61]])

In [30]:
# Accuracy
gb.score(X_test, y_test)

0.8430493273542601

In [31]:
df_fair['score'] = gb.predict(X_test)

# get_crosstabs returns a dataframe of the group counts and group value bias metrics.
xtab, _ = g.get_crosstabs(df_fair, attr_cols=attributes_to_audit)
bdf = b.get_disparity_predefined_groups(xtab, original_df=df_fair, ref_groups_dict=attributes_and_reference_groups)

ap.disparity(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

get_disparity_predefined_group()


alt.LayerChart(...)

In [32]:
ap.absolute(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

alt.LayerChart(...)

#KNN Classifier

In [33]:
KNeighborsClassifier
kn = KNeighborsClassifier()
kn.fit(X_train, y_train)

KNeighborsClassifier()

In [34]:
# Test Data
sklearn_metrics.confusion_matrix(y_test, kn.predict(X_test))

array([[116,  23],
       [ 25,  59]])

In [35]:
# Accuracy
kn.score(X_test, y_test)

0.7847533632286996

In [36]:
df_fair['score'] = kn.predict(X_test)

# get_crosstabs returns a dataframe of the group counts and group value bias metrics.
xtab, _ = g.get_crosstabs(df_fair, attr_cols=attributes_to_audit)
bdf = b.get_disparity_predefined_groups(xtab, original_df=df_fair, ref_groups_dict=attributes_and_reference_groups)

ap.disparity(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

get_disparity_predefined_group()


alt.LayerChart(...)

In [37]:
ap.absolute(bdf, metrics, 'Age_Level', fairness_threshold = disparity_tolerance)

alt.LayerChart(...)

In [38]:
X_test[0]

array([ 0.83012938, -0.01241996, -0.46037161, -0.47720996, -0.35409895,
       -0.42696708,  0.72705166,  2.1814263 , -0.05479966, -0.31414043,
       -1.65915912])

In [39]:
X[0][5]

0.0

In [43]:
df1.head(20)

Survived  Pclass        Age  SibSp  Parch     Fare  Children  Sex_male  \
0          0       3  22.000000      1      0   7.2500         0         1   
1          1       1  38.000000      1      0  71.2833         0         0   
2          1       3  26.000000      0      0   7.9250         0         0   
3          1       1  35.000000      1      0  53.1000         0         0   
4          0       3  35.000000      0      0   8.0500         0         1   
5          0       3  29.699118      0      0   8.4583         0         1   
6          0       1  54.000000      0      0  51.8625         0         1   
7          0       3   2.000000      3      1  21.0750         1         1   
8          1       3  27.000000      0      2  11.1333         0         0   
9          1       2  14.000000      1      0  30.0708         1         0   
10         1       3   4.000000      1      1  16.7000         1         0   
11         1       1  58.000000      0      0  26.5500         0         0   
12         0       3  20.000000      0      0   8.0500         0         1   
13         0       3  39.000000      1      5  31.2750         0         1   
14         0       3  14.000000      0      0   7.8542         1         0   
15         1       2  55.000000      0      0  16.0000         0         0   
16         0       3   2.000000      4      1  29.1250         1         1   
17         1       2  29.699118      0      0  13.0000         0         1   
18         0       3  31.000000      1      0  18.0000         0         0   
19         1       3  29.699118      0      0   7.2250         0         0   

    Embarked_C  Embarked_Empty  Embarked_Q  Embarked_S  
0            0               0           0           1  
1            1               0           0           0  
2            0               0           0           1  
3            0               0           0           1  
4            0               0           0           1  
5            0               0           1           0  
6            0               0           0           1  
7            0               0           0           1  
8            0               0           0           1  
9            1               0           0           0  
10           0               0           0           1  
11           0               0           0           1  
12           0               0           0           1  
13           0               0           0           1  
14           0               0           0           1  
15           0               0           0           1  
16           0               0           1           0  
17           0               0           0           1  
18           0               0           0           1  
19           1               0           0           0

In [41]:
df1.columns

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Children',
       'Sex_male', 'Embarked_C', 'Embarked_Empty', 'Embarked_Q', 'Embarked_S'],
      dtype='object')

In [ ]:
# metrics.confusion_matrix(y_test, kn.predict(df_sr.to_numpy()))